import type { Metadata } from "next";
import "./globals.css";
import TopBar from "./_components/TopBar";
import { Exo } from 'next/font/google'
import NavBar from "./_components/NavBar";
import Footer from "./_components/Footer";

const exo = Exo({
  subsets: ['latin'],
  weight: '500'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${exo.className} antialiased`}>
        <TopBar/>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
